### ISSUE TITLE
Question: How do I submit my own inuitcss components?

### ISSUE THREAD

**Issue by zomars** [inuitcss/template#1]

**Comment by csshugs** [comment]
@zomars 
First of all: This is not the appropriate repository for your question. Please just file issues in this repository that concern this repositorys purpose. For general questions such as yours, please head over to [the frameworks repo](https://github.com/inuitcss/inuitcss).

Anyway, I try to answer your question:
If you think you got some module what you consider worth it being incorporated into inuitcss, feel free to present your idea in the form of an issue in the [framework repo](https://github.com/inuitcss/inuitcss). Also have a look at the [CONTRIBUTING file](https://github.com/inuitcss/inuitcss/blob/develop/CONTRIBUTING.md).

If you want to provide your own inuitcss module as a dependency—via npm or bower or whatever is fancy at the moment—please feel free to do so, but please always be compliant to [the license](https://github.com/inuitcss/inuitcss/blob/develop/LICENSE). This is really the only thing I can give you on your way, since we don't have any final instructions of how to provide any inuitcss plugins at the moment.

Is this what you wanted to know?
